ALTER TABLE interventions_history
  ADD COLUMN IF NOT EXISTS version SERIAL NOT NULL,
  ADD COLUMN IF NOT EXISTS lot_old TEXT,
  ADD COLUMN IF NOT EXISTS lot_new TEXT,
  ADD COLUMN IF NOT EXISTS task_old TEXT,
  ADD COLUMN IF NOT EXISTS task_new TEXT,
  ADD COLUMN IF NOT EXISTS state_old TEXT,
  ADD COLUMN IF NOT EXISTS state_new TEXT;
